const choferes = [
  { Header: "DOC", accessor: "DOC", width: 80 },
  { Header: "SEXO", accessor: "SEXO", width: 60 },
  { Header: "NACIONALID", accessor: "NACIONALID", width: 60 },
  { Header: "APELLIDO", accessor: "APELLIDO", width: 100 },
  { Header: "NOMBRE", accessor: "NOMBRE", width: 120 },
  { Header: "CALLENRO", accessor: "CALLENRO", width: 100 },
  { Header: "CALLENRO2", accessor: "CALLENRO2", width: 60 },
  { Header: "CALLE", accessor: "CALLE" },
  { Header: "NUMERO", accessor: "NUMERO", width: 60 },
  { Header: "PISO", accessor: "PISO", width: 60 },
  { Header: "DEPARTAMENTO", accessor: "DEPARTAMENTO", width: 60 },
  { Header: "TELEFONO", accessor: "TELEFONO" },
  { Header: "TELEFONO2", accessor: "TELEFONO2" },
  { Header: "CELULAR", accessor: "CELULAR" },
  { Header: "CODPOSTAL", accessor: "CODPOSTAL" },
  { Header: "LOCALIDAD", accessor: "LOCALIDAD" },
  { Header: "MAIL", accessor: "MAIL" },
  { Header: "PARTIDO", accessor: "PARTIDO" },
  { Header: "PROVINCIA", accessor: "PROVINCIA" },
  { Header: "PROVINCIA_DES", accessor: "PROVINCIA_DES" },
  { Header: "FECHANAC", accessor: "FECHANAC" },
  { Header: "TIPOREG", accessor: "TIPOREG", width: 50 },
  { Header: "REGCONDUCT", accessor: "REGCONDUCT", width: 100 },
  { Header: "REGEXPEPOR", accessor: "REGEXPEPOR", width: 100 },
  { Header: "REGVALIHAS", accessor: "REGVALIHAS", width: 100 },
  { Header: "DGI", accessor: "DGI", width: 50 },
  { Header: "EMPRENOM", accessor: "EMPRENOM" },
  { Header: "EMPRECUIT", accessor: "EMPRECUIT" },
  { Header: "EMPREDIR", accessor: "EMPREDIR" },
  { Header: "EMPRELOC", accessor: "EMPRELOC" },
  { Header: "CARATULA", accessor: "CARATULA", width: 50 },
  { Header: "TIPO", accessor: "TIPO", width: 50 }
];

const examenes = [
  { Header: "DOC", accessor: "DOC" },
  { Header: "FECHREVMED", accessor: "FECHREVMED" },
  { Header: "FECHREVORI", accessor: "FECHREVORI" },
  { Header: "CATEGORIA", accessor: "CATEGORIA" },
  { Header: "LICVALIHAS", accessor: "LICVALIHAS" },
  { Header: "ESTADOMED", accessor: "ESTADOMED" },
  { Header: "CONDICIONADO", accessor: "CONDICIONADO" },
  { Header: "LIMITADO", accessor: "LIMITADO" },
  { Header: "JUDICIAL", accessor: "JUDICIAL" },
  { Header: "SUBCATE1", accessor: "SUBCATE1" },
  { Header: "SUBCATE1OL", accessor: "SUBCATE1OL" },
  { Header: "SUBCATE1TP", accessor: "SUBCATE1TP" },
  { Header: "SUBCATE1TR", accessor: "SUBCATE1TR" },
  { Header: "SUBCATE2", accessor: "SUBCATE2" },
  { Header: "SUBCATE2LD", accessor: "SUBCATE2LD" },
  { Header: "SUBCATE2TR", accessor: "SUBCATE2TR" },
  { Header: "SUBCATE3", accessor: "SUBCATE3" },
  { Header: "SUBCATE4", accessor: "SUBCATE4" },
  { Header: "SUBCATE5", accessor: "SUBCATE5" },
  { Header: "SUBCATE6", accessor: "SUBCATE6" },
  { Header: "SUBCATE7", accessor: "SUBCATE7" },
  { Header: "SUBCATE8", accessor: "SUBCATE8" },
  { Header: "TIPO", accessor: "TIPO" },
  { Header: "VISION", accessor: "VISION" },
  { Header: "VIGENREAL", accessor: "VIGENREAL" },
  { Header: "ANIOSVIGEN", accessor: "ANIOSVIGEN" },
  { Header: "NROEXAMEN", accessor: "NROEXAMEN" },
  { Header: "FECPROXEX1", accessor: "FECPROXEX1" },
  { Header: "FECPROXEX2", accessor: "FECPROXEX2" },
  { Header: "CODPRESTAD", accessor: "CODPRESTAD" },
  { Header: "DIRMED", accessor: "DIRMED" },
  { Header: "DIRPROFE", accessor: "DIRPROFE" },
  { Header: "MEDLABO", accessor: "MEDLABO" },
  { Header: "MEDPROFE", accessor: "MEDPROFE" },
  { Header: "NOMDISK", accessor: "NOMDISK" },
  { Header: "EMPRENOM", accessor: "EMPRENOM" },
  { Header: "EMPRECUIT", accessor: "EMPRECUIT" },
  { Header: "EMPREDIR", accessor: "EMPREDIR" },
  { Header: "EMPRELOC", accessor: "EMPRELOC" },
  { Header: "DGI", accessor: "DGI" },
  { Header: "FECHAENV", accessor: "FECHAENV" },
  { Header: "FECPROCESO", accessor: "FECPROCESO" },
  { Header: "NROENVIOPRES", accessor: "NROENVIOPRES" },
  { Header: "NROENVIOPRESvie", accessor: "NROENVIOPRESvie" },
  { Header: "DIASLIMI", accessor: "DIASLIMI" },
  { Header: "ESTADOFC", accessor: "ESTADOFC" },
  { Header: "ESTADOO", accessor: "ESTADOO" },
  { Header: "ESTADOA", accessor: "ESTADOA" },
  { Header: "ESTADON", accessor: "ESTADON" },
  { Header: "ESTADOP", accessor: "ESTADOP" },
  { Header: "ESTADOCR", accessor: "ESTADOCR" },
  { Header: "CANON", accessor: "CANON" },
  { Header: "ENVIADO", accessor: "ENVIADO" },
  { Header: "FEENVIO", accessor: "FEENVIO" },
  { Header: "NROENV", accessor: "NROENV" },
  { Header: "TIPO_BOLETA", accessor: "TIPO_BOLETA" },
  { Header: "BOLETA1", accessor: "BOLETA1" },
  { Header: "FECHA1", accessor: "FECHA1" },
  { Header: "IMPORTE1", accessor: "IMPORTE1" },
  { Header: "BOLETA2", accessor: "BOLETA2" },
  { Header: "FECHA2", accessor: "FECHA2" },
  { Header: "IMPORTE2", accessor: "IMPORTE2" },
  { Header: "ENVIADOCAP", accessor: "ENVIADOCAP" },
  { Header: "FEENVIOCAP", accessor: "FEENVIOCAP" },
  { Header: "NROENVCAP", accessor: "NROENVCAP" },
  { Header: "SALTEA_CTROL", accessor: "SALTEA_CTROL" },
  { Header: "DIGITAL", accessor: "DIGITAL" },
  { Header: "FECHA_MODI", accessor: "FECHA_MODI" }
];

const cursadas = [
  { Header: "IDDoc", accessor: "IDDoc" },
  { Header: "IDCurso", accessor: "IDCurso", width: 60 },
  { Header: "Fecha_Inicio", accessor: "Fecha_Inicio" },
  { Header: "Fecha_Inscripcion", accessor: "Fecha_Inscripcion" },
  { Header: "Estado", accessor: "Estado", width: 60 },
  { Header: "Fecha_Final", accessor: "Fecha_Final" },
  { Header: "Vencimiento", accessor: "Vencimiento" },
  { Header: "IDEscuela", accessor: "IDEscuela", width: 80 },
  { Header: "Tipo_Curso", accessor: "Tipo_Curso", width: 60 },
  { Header: "Derecho", accessor: "Derecho", width: 60 },
  { Header: "Canon", accessor: "Canon", width: 60 },
  { Header: "Cuit", accessor: "Cuit" },
  { Header: "IDTipo_Vehiculo", accessor: "IDTipo_Vehiculo", width: 60 },
  { Header: "Fecha", accessor: "Fecha" },
  { Header: "IDUsuario", accessor: "IDUsuario", width: 60 },
  { Header: "enviado", accessor: "enviado", width: 60 },
  { Header: "feenvio", accessor: "feenvio" },
  { Header: "nroenv", accessor: "nroenv", width: 60 }
];

const curso = [
  { Header: "DOC", accessor: "DOC" },
  { Header: "VIGENCIA", accessor: "VIGENCIA" },
  { Header: "APELLIDO", accessor: "APELLIDO" },
  { Header: "CATEGORIA", accessor: "CATEGORIA", width: 80 },
  { Header: "SUBCATE", accessor: "SUBCATE", width: 80 },
  { Header: "RECEPCION", accessor: "RECEPCION" },
  { Header: "ENVIO", accessor: "ENVIO", width: 80 },
  { Header: "ENVIADO", accessor: "ENVIADO", width: 80 },
  { Header: "FEENVIO", accessor: "FEENVIO" },
  { Header: "NROENV", accessor: "NROENV", width: 80 }
];

export default { choferes, examenes, cursadas, curso };
